markdown: kramdown
highlighter: rouge
url: "https://wizarddos-infosec.netlify.app" 
plugins:
  - jekyll-sitemap
  - jekyll-feed
collections: 
  series:
    output: true
  categories:
    output: true
